-- Removes the obsolete uniqueness rule on clientSocialContent.
--
-- OLD RULE (now proven wrong by real testing): one clientSocialContent row
-- per (clientId, contentDate, platformId, featureId) -- enforced by the
-- unique key uqClientSocialContentSlot, and mirrored by an application-level
-- clash guard in SocialContentEngine::saveEntry().
--
-- NEW RULE: clientSocialContent.id is the sole identity of an actual content
-- record. Multiple independent records may legitimately share the same
-- client/date/platform/feature (e.g. three separate Instagram Posts planned
-- and produced for the same client on the same day) -- the Calendar plan is
-- a MINIMUM requirement, not a uniqueness constraint or a cap. This unique
-- key directly blocked that and must go; nothing replaces it -- the primary
-- key (id) is sufficient identity, exactly as for any other row.
--
-- idxClientSocialContentClientDate (a plain, non-unique index on
-- clientId+contentDate, kept for lookup performance) and every FK constraint
-- are untouched by this migration -- only the UNIQUE key is dropped.
--
-- Plain DDL, same convention as this repo's other structural migrations:
-- run once per environment; re-running after it has already applied will
-- error (index no longer exists), which is expected.

ALTER TABLE clientSocialContent DROP INDEX uqClientSocialContentSlot;
